### ISSUE TITLE
How do it works?

### ISSUE THREAD

**Issue by PH7-Jack** [haringsrob/laravel-dev-tools#2] opened 2022-09-02 13:07 UTC
It has worked one time for me, but now it's not working
![image](https://user-images.githubusercontent.com/38913462/188152587-e0759191-7b4f-4a67-b37f-1a59ae538a3f.png)

**Comment by haringsrob** [comment] 2022-09-09 05:48
Hi,

Not sure what could be the cause of this. Currently there is no logging that we can activate on the fly to figure this out.

It could be due to laravel not being bootable at the moment of auto completing. Restarting the editor might work.

Let me know if you made it work.

**Comment by haringsrob** [comment] 2023-04-14 09:43
Closing for now as I fixed few bugs. Let me know if the issue persists.

**Closed by haringsrob** 2023-04-14 09:43 UTC

**Comment by gsihaj5** [comment] 2023-05-21 05:36
hi, im trying to use this package, i got problem with understanding project must be "bootable" can i got some help ?
